apiVersion: apps/v1
kind: Deployment
metadata:
 name: pwrstat-pushgateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pwrstat-pushgateway
  template:
    metadata:
      labels:
        app: pwrstat-pushgateway
    spec:
      containers:
      - name: prom-pushgateway
        image: prom/pushgateway:v0.7.0
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pwrstat-pushgateway
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: pwrstat-pushgateway
